baseurl = "/"
languageCode = "en-us"
title = "Jayaram Kancherla"
theme = "hugo-xmin"
googleAnalytics = "UA-113316814-1 "
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
# [[menu.main]]
#     name = "About"
#     url = "/about/"
#     weight = 2
# [[menu.main]]
#     name = "About"
#     url = "/about/"
#     weight = 3
# [[menu.main]]
#     name = "Publications"
#     url = "/publications/"
#     weight = 4
# [[menu.main]]
#     name = "FAQ"
#     url = "/faq/"
#     weight = 5
# [[menu.main]]
#     name = "Tags"
#     url = "/tags/"
#     weight = 5
[[menu.main]]
    name = "Blog"
    url = "/post/"
#     weight = 6
[[menu.main]]
    name = "RSS"
    url = "/index.xml"

[params]
    description = "I am currently a Faculty Researcher/Scientific Programmer with Dr. [Hector Corrada Bravo](http://www.hcbravo.org) at the Center for Bioinformatics and Computational Biology, University of Maryland, College Park. I primarily work as the lead developer on the [Epiviz framework](http://www.epiviz.org), developing interactive and integrative visual and exploratory tools for biomedical datasets (epigenomic and metagenomics)."
    footer = "&copy; [Jayaram Kancherla](https://jkanche.com) 2018 -- 2020 | [Github](https://github.com/jkanche) | [Twitter](https://twitter.com/jayaram) | modified theme from [hugo-XMin](https://github.com/yihui/hugo-xmin)"

[markup.goldmark.renderer]
    unsafe= true